import uuid
import logging
from datetime import datetime, timedelta
from typing import Optional, Dict, Any
from database.connection import db

logger = logging.getLogger("Klaud.LicenseManager")

class LicenseManager:
    """
    Manages the KLAUD licensing lifecycle.
    Handles generation, redemption, and multi-tier access validation.
    """
    
    @staticmethod
    async def ensure_db():
        """Internal safety check to ensure DB pool readiness."""
        if db.pool is None:
            await db.connect()

    @staticmethod
    async def has_access(guild_id: Optional[int]) -> bool:
        """
        Validates if a server is authorized to use KLAUD services.
        Required by all moderation and AI cogs.
        """
        if not guild_id:
            return False
            
        await LicenseManager.ensure_db()
        try:
            async with db.pool.acquire() as conn:
                row = await conn.fetchrow(
                    "SELECT active, expires_at FROM licenses WHERE server_id = $1", 
                    guild_id
                )
                
                if not row:
                    return False
                
                is_active = row['active']
                is_not_expired = row['expires_at'] > datetime.now()
                
                return is_active and is_not_expired
        except Exception as e:
            logger.error(f"Access validation error for guild {guild_id}: {e}")
            return False

    @staticmethod
    async def require_paid(guild_id: Optional[int]) -> bool:
        """
        Checks for 'paid' tier features (Premium AI, Custom Prompts).
        Required by setup_verify and admin_ai cogs.
        """
        if not guild_id:
            return False
            
        await LicenseManager.ensure_db()
        try:
            async with db.pool.acquire() as conn:
                row = await conn.fetchrow(
                    "SELECT mode, active, expires_at FROM licenses WHERE server_id = $1", 
                    guild_id
                )
                
                if row and row['active'] and row['mode'] == 'paid':
                    return row['expires_at'] > datetime.now()
                return False
        except Exception as e:
            logger.error(f"Paid tier validation error for guild {guild_id}: {e}")
            return False

    @staticmethod
    async def generate_license(mode: str, duration_days: int, creator_id: int) -> str:
        """
        Generates a unique license key for the KLAUD Owner.
        Keys are stored in pending_licenses until redeemed via /license redeem.
        """
        await LicenseManager.ensure_db()
        new_key = f"KLAUD-{uuid.uuid4().hex[:16].upper()}"
        
        try:
            async with db.pool.acquire() as conn:
                await conn.execute(
                    """INSERT INTO pending_licenses (license_key, mode, duration_days, created_by) 
                       VALUES ($1, $2, $3, $4)""",
                    new_key, mode.lower(), duration_days, creator_id
                )
            logger.info(f"New {mode} license generated by {creator_id}: {new_key}")
            return new_key
        except Exception as e:
            logger.error(f"License generation failed: {e}")
            raise e

    @staticmethod
    async def redeem_license(guild_id: int, key: str, user_id: int) -> Dict[str, Any]:
        """
        Core Redemption Logic. 
        Binds a pending key to a specific server_id and activates it.
        """
        await LicenseManager.ensure_db()
        async with db.pool.acquire() as conn:
            async with conn.transaction():
                # Check if key exists and is valid
                pending = await conn.fetchrow(
                    "SELECT mode, duration_days FROM pending_licenses WHERE license_key = $1", 
                    key
                )
                
                if not pending:
                    return {"success": False, "message": "Invalid or already redeemed license key."}
                
                mode = pending['mode']
                days = pending['duration_days']
                expiry = datetime.now() + timedelta(days=days)
                
                # Update or Insert into active licenses
                await conn.execute(
                    """INSERT INTO licenses (server_id, license_key, mode, expires_at, active, activated_at, owner_id) 
                       VALUES ($1, $2, $3, $4, $5, $6, $7)
                       ON CONFLICT (server_id) DO UPDATE SET 
                       license_key = $2, mode = $3, expires_at = $4, active = $5, activated_at = $6, owner_id = $7""",
                    guild_id, key, mode, expiry, True, datetime.now(), user_id
                )
                
                # Remove from pending to prevent double-use
                await conn.execute("DELETE FROM pending_licenses WHERE license_key = $1", key)
                
                logger.info(f"Server {guild_id} redeemed {mode} license. Expires: {expiry}")
                return {"success": True, "mode": mode, "expiry": expiry}

    @staticmethod
    async def get_license_info(guild_id: int) -> Optional[asyncpg.Record]:
        """Retrieves full license metadata for a specific guild."""
        await LicenseManager.ensure_db()
        return await db.fetchrow("SELECT * FROM licenses WHERE server_id = $1", guild_id)
