import uuid
import logging
import asyncpg  # FIXED: Added missing import for type hints and functionality
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, Union
from database.connection import db

# Production logging for the licensing subsystem
logger = logging.getLogger("Klaud.LicenseManager")

class LicenseManager:
    """
    KLAUD-NINJA Core Licensing Subsystem.
    Responsible for cryptographic key validation, server binding, and 
    feature-access authorization across all bot modules.
    """
    
    @staticmethod
    async def ensure_db():
        """
        Internal safety gateway to ensure the database pool is initialized 
        before any transaction occurs.
        """
        if db.pool is None:
            logger.info("Database pool not found. Initializing connection via LicenseManager...")
            await db.connect()

    @staticmethod
    async def has_access(guild_id: Optional[int]) -> bool:
        """
        Validates basic server authorization.
        Checks if a guild has an active entry in the licenses table that is not expired.
        """
        if not guild_id:
            return False
            
        await LicenseManager.ensure_db()
        try:
            async with db.pool.acquire() as conn:
                row = await conn.fetchrow(
                    "SELECT active, expires_at FROM licenses WHERE server_id = $1", 
                    guild_id
                )
                
                if not row:
                    return False
                
                # Validation logic: Must be flagged active AND current time must be before expiry
                is_active = row['active']
                is_not_expired = row['expires_at'] > datetime.now()
                
                return is_active and is_not_expired
        except Exception as e:
            logger.error(f"CRITICAL: Access validation failed for guild {guild_id}: {e}")
            return False

    @staticmethod
    async def require_paid(guild_id: Optional[int]) -> bool:
        """
        Validates eligibility for Premium (Paid) tier features.
        Used for Gemini Pro analysis, custom prompts, and advanced automation.
        """
        if not guild_id:
            return False
            
        await LicenseManager.ensure_db()
        try:
            async with db.pool.acquire() as conn:
                row = await conn.fetchrow(
                    "SELECT mode, active, expires_at FROM licenses WHERE server_id = $1", 
                    guild_id
                )
                
                # Logic: Must be 'paid' mode, active, and within expiration date
                if row and row['active'] and row['mode'] == 'paid':
                    return row['expires_at'] > datetime.now()
                return False
        except Exception as e:
            logger.error(f"CRITICAL: Paid tier validation failed for guild {guild_id}: {e}")
            return False

    @staticmethod
    async def generate_license(mode: str, duration_days: int, creator_id: int) -> str:
        """
        Cryptographic License Generation.
        Generates a secure, unique key stored in pending_licenses until redeemed.
        Only accessible by the Bot Owner (Authority ID).
        """
        await LicenseManager.ensure_db()
        
        # Generation of a unique 16-character hex suffix for the KLAUD prefix
        unique_id = uuid.uuid4().hex[:16].upper()
        new_key = f"KLAUD-{unique_id}"
        
        try:
            async with db.pool.acquire() as conn:
                await conn.execute(
                    """INSERT INTO pending_licenses (license_key, mode, duration_days, created_by) 
                       VALUES ($1, $2, $3, $4)""",
                    new_key, mode.lower(), duration_days, creator_id
                )
            logger.info(f"🔑 License {new_key} [{mode}] generated by Admin {creator_id}")
            return new_key
        except Exception as e:
            logger.error(f"License generation failed: {e}")
            raise e

    @staticmethod
    async def redeem_license(guild_id: int, key: str, user_id: int) -> Dict[str, Any]:
        """
        Redemption and Server Binding.
        Moves a license from 'pending' to 'active' and binds it to a specific Discord Guild.
        Uses a transaction to ensure atomicity (all or nothing).
        """
        await LicenseManager.ensure_db()
        
        async with db.pool.acquire() as conn:
            async with conn.transaction():
                # Verify key existence and status
                pending = await conn.fetchrow(
                    "SELECT mode, duration_days FROM pending_licenses WHERE license_key = $1", 
                    key
                )
                
                if not pending:
                    logger.warning(f"Failed redemption attempt: Key {key} by User {user_id} in Guild {guild_id}")
                    return {"success": False, "message": "Key is invalid, already redeemed, or expired."}
                
                mode = pending['mode']
                days = pending['duration_days']
                expiry_date = datetime.now() + timedelta(days=days)
                
                # Perform the upsert into the active licenses table
                await conn.execute(
                    """INSERT INTO licenses (server_id, license_key, mode, expires_at, active, activated_at, owner_id) 
                       VALUES ($1, $2, $3, $4, $5, $6, $7)
                       ON CONFLICT (server_id) DO UPDATE SET 
                       license_key = $2, mode = $3, expires_at = $4, active = $5, activated_at = $6, owner_id = $7""",
                    guild_id, key, mode, expiry_date, True, datetime.now(), user_id
                )
                
                # Atomic cleanup: Remove key from pending so it cannot be reused
                await conn.execute("DELETE FROM pending_licenses WHERE license_key = $1", key)
                
                logger.info(f"✅ LICENSE REDEEMED: Guild {guild_id} activated {mode} tier until {expiry_date}")
                return {"success": True, "mode": mode, "expiry": expiry_date}

    @staticmethod
    async def get_license_info(guild_id: int) -> Optional[asyncpg.Record]:
        """
        Retrieves full license metadata for a specific guild.
        Used for administrative overview and status commands.
        """
        await LicenseManager.ensure_db()
        try:
            async with db.pool.acquire() as conn:
                return await conn.fetchrow("SELECT * FROM licenses WHERE server_id = $1", guild_id)
        except Exception as e:
            logger.error(f"Error fetching license info for {guild_id}: {e}")
            return None
